name: zstu
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  sqflite: any
  connectivity: any
  path_provider: any
  mockito: any

  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/faculties/FICT.png
    - assets/faculties/FEM.png
    - assets/faculties/MEF.png
    - assets/faculties/FME.png
    - assets/faculties/FAF.png
    - assets/nav/about.png
    - assets/nav/faculties.png
    - assets/nav/learnPortal.png
    - assets/nav/mySchedule.png
    - assets/nav/news.png
    - assets/nav/schedule.png
    - assets/nav/settings.png
    - assets/nav/teachers.png
    - assets/nav/header.png
